query CHALLENGES_QUERY {
  challengesQuery: challenges {
    id
    creator
    startTimestamp
    endTimestamp
    title
    videos {
      id
      creator {
        id
      }
      challenge
      uploadTimestamp
    }
  }
}

query CHALLENGE_BY_ID($id: String!){
  challengeByIdQuery: challenge(id : $id) {
    id
    creator
    endTimestamp
    startTimestamp
    title
    description
    beneficiary
    minEntryFee
    numChallengers
    isPublic
    totalFund
    winner
    isActive
    videos(orderBy: uploadTimestamp, orderDirection : desc) {
      id
      creator {
        id
      }
      uploadTimestamp
    }
  }
}
