query CHALLENGE_BY_ID($id: String!){
  challengeById: challenge(id : $id) {
   	id
    numChallengers
    title
    description
    minEntryFee
    totalFund
    videos(first:3) {
     	id
      creator {
        id
      }
    }
  }
}
